# Generated by Django 4.1.2 on 2024-07-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopta_un_peludo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
